name: Gerar APK Android

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Baixar o Código
        uses: actions/checkout@v4

      - name: 2. Preparar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 3. Instalar Dependências e Construir Web
        run: |
          npm install
          npm run build

      - name: 4. Preparar o Java e Android
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: 5. Sincronizar Capacitor
        run: |
          npm install @capacitor/android
          npx cap add android || true
          npx cap sync android

      - name: 5.5 Injetar Licença de GPS no Android
        run: |
          sed -i 's/<application/<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" \/>\n    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" \/>\n    <application/g' android/app/src/main/AndroidManifest.xml

      - name: 6. Compilar o APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: 7. Salvar e Entregar o APK
        uses: actions/upload-artifact@v4
        with:
          name: VizinApp-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
